### ISSUE TITLE
Connect to snowflake using pivate_key instead of password

### ISSUE THREAD

**Issue by mckuzyk** [elixir-explorer/adbc#101]
With the snowflake python connector, it's possible to create a connection using a private key, for examlpe in this [how-to](https://community.snowflake.com/s/article/How-To-Connect-to-Snowflake-using-key-pair-authentication-directly-using-the-private-key-incode-with-the-Python-Connector). Does an equivalent exist here? I see references to using a private key in the [ADBC documentation](https://arrow.apache.org/adbc/main/driver/snowflake.html#client-options)

**Comment by josevalim** [comment]
The same keys in ADBC documentation are supported here. So please give it a try and let us know how it goes.

**Comment by mckuzyk** [comment]
Thank you for the information Jose. I gave it a shot and failed. I apologize if I'm way off on this, I'm a novice Elixir user! I tried the following snippet to test:

```elixir
kw = [
  {:driver, :snowflake},
  {:username, "..."}
  {:"adbc.snowflake.sql.account", "..."},
  {:"adbc.snowflake.sql.client_option.jwt_private_key", "/path/to/key"}
]

{:ok, db} = Adbc.Database.start_link(kw)
```

Which produced
```elixir
{:error, #Adbc.Error<message: "[Snowflake] AdbcDatabaseInit: Go panic in Snowflake driver (see stderr): \"invalid memory address or nil pointer dereference\"", vendor_code: 0, ...>}
```

This is probably a separate issue but I also tried to connect w/ SSO. In that case `Adbc.Database.start_link(...)` runs successfully, but `Adbc.Connection.start_link(database: db)` results in `[Snowflake] authentication timed out`, and the browser popup that should appear never does.

**Comment by cocoa-xu** [comment]
Hi @mckuzyk, thanks for reporting this. I’ll try to set up one and see how it goes with snowflakes.
