### ISSUE TITLE
Is postgres INSERT with params supported?

### ISSUE THREAD

**Issue by ozitrance** [elixir-explorer/adbc#105]
I'm trying to use this library with simple INSERT query, using params, something like this:
```
      query = "INSERT INTO example VALUES ($1, $2, $3)"
      {:ok, query} =
        Adbc.Connection.query(
          MyApp.Conn,
          query,
          [1, 2, 3]
        )
       result = query |> Adbc.Result.materialize
```

I keep getting an error saying **no params were provided but query required 3**, or something like that... 

Feels like a bug or maybe it's not supported yet? 

Thank you!

**Comment by cocoa-xu** [comment]
Hi @ozitrance, thanks for reporting this issue! And it seems that ADBC has added the support for queries that bind parameters in https://github.com/apache/arrow-adbc/pull/2065, and we just need to bump the driver versions and do a new release!

**Comment by cocoa-xu** [comment]
v0.6.3 is shipped!
