### ISSUE TITLE
update to ADBC 15

### ISSUE THREAD

**Issue by cocoa-xu** [elixir-explorer/adbc#108]
Just saw the pre-release version of ADBC 15, https://github.com/apache/arrow-adbc/releases/tag/apache-arrow-adbc-15-rc0

 Leaving this as a reminder for myself to bump the version after ADBC 15 is official.

**Comment by josevalim** [comment]
I tried it locally and I saw some failures in the suite, we may want to take a look at them before to report in case something broke upstream.
