### ISSUE TITLE
Issue with 0.6.3 aarch64-linux precompiled nif

### ISSUE THREAD

**Issue by whitedr** [elixir-explorer/adbc#109]
I'm hitting an issue in which the symptom is very similar to what is described [here](https://github.com/elixir-explorer/adbc/issues/99#issue-2473220842).  Namely that after building a docker image for my app and trying to run it with `{:adbc, "0.6.3"}` as a dependency, the app seems to "hang" at startup.  If I Ctrl-C it and look at the proc info, I see this:

```
0x0000fffebc794ff0 Return addr 0x0000ffff66db5004 (io:put_chars/2 + 188)
y(0)     []
y(1)     [standard_io,[<<"Failed to load nif: {:load_failed, ~c\"Failed to load NIF library: '/app/lib/adbc-0.6.3/priv/adbc_nif.so: cannot open shared object file: No such file or directory'\"}">>,10]]
y(2)     #Ref<0.200537568.2251816962.111287>
```

More details on my local setup and docker environment...

As mentioned, the app is pulling in `{:adbc, "0.6.3"}`.  This  app is built in a docker image which is using `hexpm/elixir:1.17.3-erlang-26.2.5.5-debian-bookworm-20241016-slim` as the base/builder image and then using `debian:bookworm-20241016-slim` as the runtime image in a multi-stage Dockerfile.  My local dev environment is an M3 mac.  I also see the following when I build the docker image:

```
#32 47.78 ==> adbc
#32 47.78 Downloading precompiled NIF to /root/.cache/adbc-nif-2.16-aarch64-linux-gnu-0.6.3.tar.gz
#32 48.32 Compiling 9 files (.ex)
#32 48.35 Failed to load nif: {:load_failed, ~c"Failed to load NIF library: '/app/_build/prod/lib/adbc/priv/adbc_nif.so: cannot open shared object file: No such file or directory'"}
```

The build however continues after this and completes successfully.  When I then run a container (bash into it) with this image, I see that the file does in fact exist at the path in question above.  If I try to inspect the `adbc_nif.so` file with `ldd` I get this however:

```
nobody@852c36390f15:/app$ ldd -v /app/lib/adbc-0.6.3/priv/adbc_nif.so 
        not a dynamic executable
```

So it seems like the precompiled lib `adbc-nif-2.16-aarch64-linux-gnu-0.6.3.tar.gz` that was downloaded is the wrong arch (or something else is wrong with it).

If I revert the version of adbc to `{:adbc, "0.6.2"}` and build again, I see that it compiles the lib (which I believe is expected as there isn't a precompiled archive available for aarch64-linux prior to 0.6.3) and the app runs fine with the compiled 0.6.2 version.

**Comment by josevalim** [comment]
Does it work if you use main via github? That will force a build (with make, gcc and friends), but it should still be relatively fast.

@cocoa-xu is there and env var or application env we could set to force it to build by hand?

**Comment by whitedr** [comment]
Hey @josevalim, yes it works if I change the adbc dependency to: `{:adbc, git: "https://github.com/elixir-explorer/adbc", ref: "main", override: true}`.  When I do that, the library builds and it looks ok in the built docker image.

That said, I'm still wondering if there's something wrong with the `adbc-nif-2.16-aarch64-linux-gnu-0.6.3.tar.gz` precompiled archive?  I did the following to take a look...

Reset dep back to `{:adbc, "0.6.3"}` and built the docker image again.  Then run the container (shell into it) and ran the following:

```
nobody@e90e4633a65f:/app$ file lib/adbc-0.6.3/priv/adbc_nif.so 
lib/adbc-0.6.3/priv/adbc_nif.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=286e8ee888faf978e5ae754147a555fb020f651a, not stripped
```

I then set the dep to `{:adbc, git: "https://github.com/elixir-explorer/adbc", ref: "main", override: true}` and see the following running the same `file` command:

```
nobody@2994224b35d0:/app$ file lib/adbc-0.6.3/priv/adbc_nif.so 
lib/adbc-0.6.3/priv/adbc_nif.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=d8a27a113c898cff147c45fd06d055667c2bbc14, not stripped
```

Note that for `{:adbc, "0.6.3"}` the prebuilt lib that was installed is showing `x86-64` but I think that should have been `ARM aarch64` since (as I showed above) the precompiled archive file that was downloaded was `adbc-nif-2.16-aarch64-linux-gnu-0.6.3.tar.gz`.

**Comment by cocoa-xu** [comment]
> @cocoa-xu is there and env var or application env we could set to force it to build by hand?

We don't have that yet but this shouldn't happen in the beginning. I'll check the CI workflow!

**Comment by cocoa-xu** [comment]
Hi @whitedr, sorry for the late reply. It seems that the `clean` target in the Makefile didn't properly remove all relevant files before the next build target. It should be fixed in v0.6.4 now! Please let me know if v0.6.4 works for you!

**Comment by josevalim** [comment]
Thank you for the prompt fix @cocoa-xu! 🙌 

We should probably add a way to force build anyway, this may be important for those who don't want to rely on prebuilt artifacts?

**Comment by cocoa-xu** [comment]
> We should probably add a way to force build anyway, this may be important for those who don't want to rely on prebuilt artifacts?

Surely! I'll add an env var for this. Also I was wondering if we should support this in `elixir_make`, like `ELIXIR_MAKE_PRECOMPILE_ALLOWLIST` and/or `ELIXIR_MAKE_PRECOMPILE_DENYLIST`, and users can supply a comma-separated value to only allow or deny the usage of prebuilt artifacts? For example,

```bash
export ELIXIR_MAKE_PRECOMPILE_DENYLIST=adbc,stb_image
```

**Comment by josevalim** [comment]
Should we copy rustler precompiled? https://hexdocs.pm/rustler_precompiled/RustlerPrecompiled.html#module-options

So pretty much:

    config :elixir_make, :force_build, adbc: true

?

**Comment by cocoa-xu** [comment]
> Should we copy rustler precompiled? https://hexdocs.pm/rustler_precompiled/RustlerPrecompiled.html#module-options
> 
> So pretty much:
> 
> ```
> config :elixir_make, :force_build, adbc: true
> ```
> 
> ?

Got it! I'll send a PR for this to elixir_make~

**Comment by josevalim** [comment]
@cocoa-xu I pushed an env var that is consistent with Explorer here:

https://github.com/elixir-explorer/adbc/commit/30166c81c220de50446163b562f026475a633ef4

Although I realize we should probably be using PRs for those...

**Comment by josevalim** [comment]
Once we update `elixir_make`, we can update the README here too.

**Comment by cocoa-xu** [comment]
> Although I realize we should probably be using PRs for those...

Ah sorry I thought this was kinda straightforward so I only pushed some commits for it. Apologies!

**Comment by josevalim** [comment]
No worries, I did the same mistake :D I think we can close this one. Thank you!!!

**Comment by cocoa-xu** [comment]
Should I'll wait for the new release of `elixir_make` and update here? I haven't released adbc v0.6.5 on hex.pm yet.

**Comment by josevalim** [comment]
New elixir_make is out! We don’t need to do a new release though I think. We can wait until ADBC 15?

**Comment by cocoa-xu** [comment]
> New elixir_make is out! We don’t need to do a new release though I think. We can wait until ADBC 15?

Yep, lets wait for ADBC 15, it should be there soon!

**Comment by whitedr** [comment]
@cocoa-xu fyi - 0.6.4 worked just fine for me. thanks!
