### ISSUE TITLE
Specify cross-compiler for Adbc

### ISSUE THREAD

**Issue by cocoa-xu** [elixir-explorer/adbc#19]
Right now Adbc would always use /usr/bin/x86_64-linux-gnu-gcc as the compiler. I'll try it and see how do I specify cross-compiler for Adbc. We should be able to do that by specifying `CMAKE_TOOLCHAIN_FILE`.

**Comment by cocoa-xu** [comment]
Actually, there is no need to build for other Linux targets than x86_64 because we're downloading official drivers which only have support for x86_64 Linux.

**Comment by lidavidm** [comment]
Where are the drivers being downloaded from? They should build on Linux (x64/ARM), macOS (x64/ARM), and Windows (x64). We only provide binaries via conda-forge, and those packages don't yet build for Windows there (someone needs to figure out the CI issues).

**Comment by cocoa-xu** [comment]
> Where are the drivers being downloaded from? They should build on Linux (x64/ARM), macOS (x64/ARM), and Windows (x64). We only provide binaries via conda-forge, and those packages don't yet build for Windows there (someone needs to figure out the CI issues).

We currently download drivers from the release page, for example, https://github.com/apache/arrow-adbc/releases/tag/apache-arrow-adbc-0.11.0. These drivers are extracted from Python wheels.

**Comment by lidavidm** [comment]
ah, good to know, thanks. Uh, I suppose that isn't the intended use, but if it works...

**Comment by josevalim** [comment]
@lidavidm it would be nice if we could have only the drivers (outside of the wheels) but due to ADBC's design, they just work, yeah, so at least for now we don't see a reason to. :)

**Comment by josevalim** [comment]
@cocoa-xu is this still relevant?

**Comment by cocoa-xu** [comment]
> @cocoa-xu is this still relevant?

Let's close this one as we probably won't build these drivers in this repo.
