### ISSUE TITLE
Can the driver support custom path?

### ISSUE THREAD

**Issue by watsy0007** [elixir-explorer/adbc#24]
In my workflow, I use python and `duckdb` quite often, I have been considering how to migrate to Elixir for a while, Recently duckdb officially support the ADBC API and provided examples.

[DuckDB ADBC - Zero-Copy data transfer via Arrow Database Connectivity](https://duckdb.org/2023/08/04/adbc.html)
[ADBC API](https://duckdb.org/docs/api/adbc.html)

The offical C++ example is as follow:
```C++
AdbcDatabaseNew(&adbc_database, &adbc_error);
AdbcDatabaseSetOption(&adbc_database, "driver", "path/to/libduckdb.dylib", &adbc_error);
AdbcDatabaseSetOption(&adbc_database, "entrypoint", "duckdb_adbc_init", &adbc_error);
// By default, we start an in-memory database, but you can optionally define a path to store it on disk.
AdbcDatabaseSetOption(&adbc_database, "path", "test.db", &adbc_error);
AdbcDatabaseInit(&adbc_database, &adbc_error);
```
Currently, the project only supports a fixed drivers `sqlite postgresql flightsql snowflake`, Is it possible to add a driver for custom path?

for example:

```elixir
{:ok, db} =
  Kino.start_child(
    {Adbc.Database, driver: "/path/to/libduckdb-osx-universal/libduckdb.dylib", entrypoint: "duckdb_adbc_init"}
  )
{:ok, conn} = Kino.start_child({Adbc.Connection, database: db})
{:ok, result} = Adbc.Connection.query(conn, "select 1;")
```
or

```elixir
{:ok, db} =
  Kino.start_child(
    {Adbc.Database, driver: :custom, path: "/path/to/libduckdb-osx-universal/libduckdb.dylib", entrypoint: "duckdb_adbc_init"}
  )
{:ok, conn} = Kino.start_child({Adbc.Connection, database: db})
{:ok, result} = Adbc.Connection.query(conn, "select 1;")
```

**Comment by josevalim** [comment]
Yes, pull requests are welcome!

**Comment by josevalim** [comment]
Actually, I may have a fix soon!

**Comment by dlindenkreuz** [comment]
@watsy0007 Were you able to successfully set up DuckDB via ADBC in the end?

**Comment by watsy0007** [comment]
@dlindenkreuz yes. as follows
<img width="917" alt="image" src="https://github.com/elixir-explorer/adbc/assets/822237/f5636577-ad3d-4a72-9d6e-d48d98a995d2">

**Comment by dlindenkreuz** [comment]
Nice, thanks for the swift response. I found out that further keyword options are passed through to the native initializer, so I was able to specify the DB path like this:

```elixir
defmodule MyApp.Application do
  def start(_type, _args) do
    children = [
      {Adbc.Database,
       driver: "./libduckdb.dylib", # relative to cwd
       entrypoint: "duckdb_adbc_init",
       path: "./.data/duck.db",
       process_options: [name: MyApp.DuckDB]},
      {Adbc.Connection, database: MyApp.DuckDB, process_options: [name: MyApp.DuckConn]},
      # ...
```
