### ISSUE TITLE
Connect to a sqlite db

### ISSUE THREAD

**Issue by sehHeiden** [elixir-explorer/adbc#29]
I try to connect explorer 0.7 to a sqlite3 db with adbc 0.1.

```elixir
 db = Kino.start_child({Adbc.Database, driver: :sqlite, uri: "file:local_path/file.db"})
```
throws the error:

> {:error,
>  %ArgumentError{
>    message: "driver sqlite is not available (see Adbc moduledocs to learn how to install a driver)"
>  }}

Alternatives:
I tried to use an interpolated absolute path and even:
```elixir
db = Kino.start_child({Adbc.Database, driver: :sqlite, uri: ":memory:"})
```
all throw the same error. I got exqlite with fetch_all working. But that list of a list can not be used to create a DataFrame. Plus, how would I get the column  names?

**Comment by josevalim** [comment]
You must install the driver. Please see steps in the docs: https://hexdocs.pm/adbc/Adbc.html#module-installation :)
