### ISSUE TITLE
Snowflake driver download link for x86_64 is broken

### ISSUE THREAD

**Issue by sezaru** [elixir-explorer/adbc#36]
On line https://github.com/elixir-explorer/adbc/blob/6bd37beb21926c1c53b3c4974aa12fcb43da90a0/lib/adbc_driver.ex#L99C1-L99C1

```elixir
      "x86_64-linux-gnu" ->
        {:ok,
         "adbc_driver_#{driver_name}-#{version}-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"}
```

This will try to download the file https://github.com/apache/arrow-adbc/releases/download/apache-arrow-adbc-0.7.0/adbc_driver_snowflake-0.7.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

But this file doesn't exists, the correct path is https://github.com/apache/arrow-adbc/releases/download/apache-arrow-adbc-0.7.0/adbc_driver_snowflake-0.7.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl

**Comment by josevalim** [comment]
Thank you. The URLs seem to change per driver, so I will need to accommodate that accordingly.

**Comment by josevalim** [comment]
Can you please try main and let me know if it works? Then I will ship a new release.

**Comment by sezaru** [comment]
> Can you please try main and let me know if it works? Then I will ship a new release.

Working great!
