### ISSUE TITLE
List Parameter for Query

### ISSUE THREAD

**Issue by maennchen** [elixir-explorer/adbc#39]
The following code is not currently supported:

```elixir
Adbc.Connection.query(
  connection_pid,
  """
  SELECT *
  FROM posts
  WHERE id = ANY(?1::INT[])
  """,
  [[1, 2]]
)
```

=>

```elixir
{:error, %ArgumentError{message: "type not supported yet."}
```

**Comment by josevalim** [comment]
Yes, we don't support list types yet. PRs are welcome. :)

**Comment by maennchen** [comment]
I tried to take a quick stab at it, but have some issues:

* SQLite does not really support arrays except in JSON. I therefore wanted to try with Postgres
* Postgres array responses are not working: #40 
* Adbc seems not to support parameters with Postgres select at all

https://arrow.apache.org/adbc/0.5.1/python/recipe/postgresql.html#execute-a-statement-with-bind-parameters
>  Right now, the PostgreSQL driver only supports bind parameters for queries that don’t generate result sets.

**Comment by josevalim** [comment]
This is implemented I believe. Both PG support and arrow lists.
