### ISSUE TITLE
Adbc.Connection.query/3 not getting all chunks

### ISSUE THREAD

**Issue by Cowa** [elixir-explorer/adbc#44]
Queries where results are split in several chunks stop after the first one.

```elixir
%Adbc.Result{num_rows: num_rows, data: data} =
  Adbc.Connection.query!(conn, query)

# Get length of a column
num_data = data |> Enum.to_list() |> hd() |> elem(1) |> length()

IO.inspect(num_rows) # => 150452
IO.inspect(num_data) # => 495
```

On the function `Adbc.Connection.stream_results/3` when I switch the `done` status...
```elixir
case done do
  # was 0
  1 -> stream_results(reference, acc, num_rows) 
  # was 1
  0 -> {:ok, %Adbc.Result{data: acc, num_rows: num_rows}} 
end
```

... I get every chunks but it fails at the end:
```
invalid ArrowArray or ArrowSchema, values->n_children != schema->n_children
```

So I guess there is something wrong on the C implementation around this `done` status.

Tested on both PostgreSQL and Snowflake.

**Comment by josevalim** [comment]
@Cowa please try removing this line too: https://github.com/elixir-explorer/adbc/blob/a712541b158ffd48b77e1291113f9dcbfac71ed9/c_src/adbc_nif.cpp#L111-L114

And then I think it should all work. If so, a PR is welcome!

**Comment by Cowa** [comment]
It crashes the VM with a `segmentation fault` 😬

I haven't done C in a very long time, I don't know how to debug C code with gdb behind a nif.

**Comment by josevalim** [comment]
Can you please provide some commands for me to reproduce this? Maybe something that generates a bunch of rows inside PostgreSQL and then a query? It can even be a script that you run with `mix run foo.exs`.

**Comment by Cowa** [comment]
Here is a script, it generates 3_506_641 rows from a `generate_series` query, so no data is written.
https://gist.github.com/Cowa/c1cee4118930fe8c1120c0cff6382a17

**Comment by josevalim** [comment]
Fixed in main, please give it a try! TY for the test!
