### ISSUE TITLE
:flightsql Driver isn't listed in Supported Drivers in docs

### ISSUE THREAD

**Issue by benkimpel** [elixir-explorer/adbc#45]
Seems like `:flightsql` is a supported driver, but it's not listed in the docs. Any interest in a PR adding it?

**Comment by josevalim** [comment]
Feel free to submit a PR if you desire!

**Comment by josevalim** [comment]
I will go ahead and close this one, as I personally have no experience with flightsql. But feel free to PR!

**Comment by benkimpel** [comment]
Thanks, @josevalim. I'll open a PR for a doc update when I get a chance. Probably over the holidays.
