### ISSUE TITLE
Usage with connection pool?

### ISSUE THREAD

**Issue by dlindenkreuz** [elixir-explorer/adbc#47]
This library is currently built to use one connection per process. Are there any reasons why I should *not* try to integrate it with a connection pool (thinking of [db_connection](https://github.com/elixir-ecto/db_connection))?

Or do any of the maintainers plan to provide an official way to integrate ADBC with a connection pool?

**Comment by josevalim** [comment]
There are no plans at the moment because each databases in ADBC give different guarnatees regarding concurrent reads and so on. So we decided to keep this one low-level. You can add pooling on top, perhaps via tools like poolboy.

**Comment by dlindenkreuz** [comment]
I was able to hack together a driver that uses db_connection and a working Ecto adapter that delegates most callbacks to `Ecto.Adapters.Postgres` 🤓 will consider sharing once the implementation is a bit more mature.
