### ISSUE TITLE
Need support for custom certs

### ISSUE THREAD

**Issue by GenericJam** [elixir-explorer/adbc#71]
This line is giving me grief as it makes the download fail and then I have to track it down.

https://github.com/elixir-explorer/adbc/blob/c538b55dea8b3c260e3941ad05263ef185a75a9c/lib/adbc_helper.ex#L62

If I comment it out it will work for me as I've already created a mix task that patches my company's certs into `"priv/cacerts.pem"`.

It would be much more convenient if I could specify the cert and/or it gets pulled from an env var such as `HEX_CACERTS_PATH`.

This is on the latest versions  Elixir 1.16.2 Erlang 26.2.4

Thank you.

**Comment by josevalim** [comment]
Please send a PR that adds ADBC_CACERTS_PATH. But you will probably have better luck changing Erlang's default store OR allowing the path for the default store in Erlang to be configured.

**Comment by GenericJam** [comment]
How do I change the Erlang default store? Is this a recent addition to Erlang?

**Comment by josevalim** [comment]
Erlang is going to read from your system certificates, so if you add it to your OS Certificate Store, it should be enough!
