### ISSUE TITLE
Year range for some date/time format

### ISSUE THREAD

**Issue by cocoa-xu** [elixir-explorer/adbc#74]
I was testing the `tdD` format (number of days represents in `int32_t` integers) in adbc. It supports up to year 5874897 AD (like [the upper limit in postgresql](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME)). However, as we're using `Calendar.ISO` (hence `Calendar.ISO.parse_date/1`) in Elixir it only supports year from -9999 to 9999.

Similar issues exist for timestamps and intervals (with different lower and upper limits).

There're potentially a few ways to fix it (if we're not going to ignore this for now):

- add an `Adbc.Date` module (and maybe copy some basic functions from `Elixir.Date` if necessary)
- store the original 32-bit integers in the query result instead of converting it to `Elixir.Date`
- add an `Adbc.Calendar` module to support it (basically copy and change some part of the `Calendar.ISO` module)

@josevalim WDYT?

**Comment by josevalim** [comment]
@cocoa-xu if I remember correctly, we can't parse dates outside of the range (due to the iso format) but we can create them directly. Would that be enough? If necessary, we can relax some guards in Elixir itself.

**Comment by cocoa-xu** [comment]
Yeah and it seems that we can only create them directly like `%Date{year: 5874897, month: 12, day: 31}`. `Date.new(5874897, 12, 31)` will return `{:error, :invalid_date}` and the `~D` sigil will raise an exception. 

```elixir
iex> ~D[5874897-12-31]
** (ArgumentError) cannot parse "5874897-12-31" as Date for Calendar.ISO, reason: :invalid_format
    (elixir 1.17.0-dev) lib/kernel.ex:6679: Kernel.maybe_raise!/4
    (elixir 1.17.0-dev) lib/kernel.ex:6658: Kernel.parse_with_calendar!/3
    (elixir 1.17.0-dev) expanding macro: Kernel.sigil_D/2
    iex:2: (file)
```

The issue if we're directly constructing a Date struct is, it won't work with some functions (that depends on `Calendar.ISO`) in `Date`. For example:

```elixir
iex> date = %Date{year: 5874897, month: 12, day: 31}
iex> Date.diff(date, ~D[2000-01-03])
** (FunctionClauseError) no function clause matching in Calendar.ISO.days_in_month/2    
    
    The following arguments were given to Calendar.ISO.days_in_month/2:
    
        # 1
        5874897
    
        # 2
        12
    
    Attempted function clauses (showing 1 out of 1):
    
        def days_in_month(year, month) when is_integer(year) and year >= -9999 and year <= 9999 and is_integer(month) and month >= 1 and month <= 12
    
    (elixir 1.17.0-dev) lib/calendar/iso.ex:856: Calendar.ISO.days_in_month/2
    (elixir 1.17.0-dev) lib/calendar/iso.ex:1944: Calendar.ISO.ensure_day_in_month!/3
    (elixir 1.17.0-dev) lib/calendar/iso.ex:806: Calendar.ISO.date_to_iso_days/3
    (elixir 1.17.0-dev) lib/calendar/date.ex:745: Date.diff/2
    iex:8: (file)
```

> we can't parse dates outside of the range (due to the iso format)

Actually, I think ISO 8601 didn't explicitly limit the year to be four-digits, and according to Wikipedia:

> *ISO 8601 prescribes, as a minimum, a four-digit year [YYYY] to avoid the [year 2000 problem](https://en.wikipedia.org/wiki/Year_2000_problem).*

Although in practice it's very rare to use year beyond this range. I can only think about one particular case for it -- when one would like to use a special value to represent a distant future/past, like `Date. distantFuture` in Swift or `infinity` in postgresql:

Input String | Valid Types | Description
-- | -- | --
epoch | date, timestamp | 1970-01-01 00:00:00+00 (Unix system time zero)
infinity | date, timestamp | later than all other time stamps
-infinity | date, timestamp | earlier than all other time stamps
now | date, time, timestamp | current transaction's start time
today | date, timestamp | midnight (00:00) today
tomorrow | date, timestamp | midnight (00:00) tomorrow
yesterday | date, timestamp | midnight (00:00) yesterday
allballs | time | 00:00:00.00 UTC

https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-VALUES

> If necessary, we can relax some guards in Elixir itself.

Can't say for sure if it's necessary or not... but I think it can be useful. Alternatively I can return original integers if they exceeds the range that `Calendar.ISO` currently allows.

Maybe we can start by adding one or two special value in Elixir, like `Date.distantFuture()` and `Date.distantPast()`?

**Comment by josevalim** [comment]
This topic came up in the past and I thought we removed the year guards everywhere except parsing. My suggestion is to remove them and, when pretty printing, if the date is outside of the range, we print as Date.new! Instead of the sigil. In any case, I think this should be tackled in Elixir :)

**Comment by cocoa-xu** [comment]
> This topic came up in the past and I thought we removed the year guards everywhere except parsing. My suggestion is to remove them (except when parsing) and, when pretty printing, if the date is outside of the range, we print as Date.new! Instead of the sigil. In any case, I think this should be tackled in Elixir :)

No problem! Would you like me to send a PR for this?

**Comment by josevalim** [comment]
If you would like to, then yes!

**Comment by kipcole9** [comment]
ISO8601 only constrains the year to exactly four digits in the implicit representation, which is what Elixir uses for the `~D` sigil. It does not constrain the number of digits in the expanded or explicit representations. 

So happy to see this addition, thank you @cocoa-xu.

**Comment by cocoa-xu** [comment]
Hi @kipcole9, it's been a while and thanks for the reply!

> ...which is what Elixir uses for the `~D` sigil. It does not constrain the number of digits in the expanded or explicit representations.

These guards are in functions like `Calendar.ISO.parse_date/1` so `Date.new/4` (and other functions like `Date.add/2`) will fail.

```elixir
iex> Date.new(10000, 1, 1)
{:error, :invalid_date}
iex> Date.add(Date.new!(9999, 12, 31), 1)
** (FunctionClauseError) no function clause matching in Calendar.ISO.date_from_iso_days/1

    The following arguments were given to Calendar.ISO.date_from_iso_days/1:

        # 1
        3652425

    Attempted function clauses (showing 1 out of 1):

        def date_from_iso_days(days) when is_integer(days) and days >= -3_652_059 and days <= 3_652_424

    (elixir 1.16.1) lib/calendar/iso.ex:812: Calendar.ISO.date_from_iso_days/1
    (elixir 1.16.1) lib/calendar/date.ex:710: Date.add/2
    iex:2: (file)
```

As for the PR https://github.com/elixir-lang/elixir/pull/13551, it didn't change the behaviour of the `~D` sigil; it relaxed the guards for other functions such as `Date.add` and `Date.shift`:

```elixir
iex> ~D[100000-01-01]
** (ArgumentError) cannot parse "100000-01-01" as Date for Calendar.ISO, reason: :invalid_format
    (elixir 1.17.0-dev) lib/kernel.ex:6679: Kernel.maybe_raise!/4
    (elixir 1.17.0-dev) lib/kernel.ex:6658: Kernel.parse_with_calendar!/3
    (elixir 1.17.0-dev) expanding macro: Kernel.sigil_D/2
    iex:1: (file)
iex> ~D[1000-01-01]
~D[1000-01-01]
iex> Date.new!(10000, 1, 1)
Date.new!(10000, 1, 1)
```

While it's usually expected four digits for the year component, the current implementation of `Calendar.ISO` is using the extended format by default, which allows calendar years before the start of the year [0000]

```elixir
iex> Calendar.ISO.parse_date("-1000-01-02")
{:ok, {-1000, 1, 2}}
```

> *By mutual agreement of the partners in information interchange, it is permitted to expand the component identifying the calendar year, which is otherwise limited to four digits. This enables reference to dates and times in calendar years outside the range supported by complete representations, i.e. before the start of the year [0000] or after the end of the year [9999].*
>
> from Section 3.5 Expansion in ISO 8601-1:2016, [web archive](https://ia601807.us.archive.org/4/items/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf)

Therefore, I think since we've already expanded the calendar year component to `[-9999, 9999]`, perhaps we can reasonably further expand it to other functions.

**Comment by kipcole9** [comment]
> By mutual agreement of the partners in information interchange, it is permitted to expand the component identifying the calendar year, which is otherwise limited to four digits. This enables reference to dates and times in calendar years outside the range supported by complete representations, i.e. before the start of the year [0000] or after the end of the year [9999].

> from Section 3.5 Expansion in ISO 8601-1:2016, [web archive](https://ia601807.us.archive.org/4/items/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf)

That is from Part 1, ISO 8601 introduces an expanded form of the implicit format. In Section 4.7:

> ISO 8601-1:2019, 5.2.2.3 allows the value of the calendar year time scale component to exceed four
digits (a year after 9999 or before -9999). However, this is allowed only by mtual agreement of the
communicating parties. This subclause addresses this specific limitation.
﻿
> An alternative time scale component for calendar year, not requiring mutual consent, is provided here
as a substitute for the [year] time scale component defined in ISO 8601-1:2019, 3.2.2. It should be used
only for dates that include the calendar year only, and only for years later th 9999 or earlier than
-9999 (otherwise the representation provided in ISO 8601-1 should be used).

> The character "Y" can be used to prefix a string to signify that the element is a calendar year.....

> EXAMPLE 1 'Y1700000002' represents a positive calendar year 1700000002.
> EXAMPLE 2 'Y-1700000002' represents a negative calendar year -1700000002.

This means that `Y700000002/12/31` is considered a valid and would be called the "expanded form of the implicit format".

Potentially `sigil_D` could be extended to support this expanded form but this is only an issue of representation. ISO8601 does not in any way constrain the value of a `year` time scale unit.  It even supports (in Part 2) exponents, and significant digits notation but I'm pretty sure thats out of scope for this PR.

**Comment by josevalim** [comment]
Thanks everyone. Closing in favor of the Elixir PR :)

**Comment by cocoa-xu** [comment]
Thanks @josevalim!

> That is from Part 1. ISO 8601 Part 2 introduces an expanded form of the implicit format. In Section 4.7:

@kipcole9 ah I see! If only we can have a somewhat simpler standard and the standard is not behind a paywall...
